---
title: "Candidate Key Statements"
resource_files:
- .httr-oauth
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---

```{r setup, include=FALSE}

library(flexdashboard)
library(tidyverse)
library(lubridate)
library(janitor)
library(glue)
library(plotly)
library(DT)
library(googlesheets)
library(kableExtra)
library(leaflet)
# library(ggmap)
library(RColorBrewer)
library(htmlwidgets)
library(htmltools)
library(tigris)
options(tigris_class = "sf")



### DATA LOADING AND PREP

# import data from Google Sheet 

#register DW's 2020 google sheet using stored sheet id key 
mykey <- Sys.getenv("DW2020_KEY")
dw2020 <- gs_key(mykey)


# INTERVIEWS/REMARKS DATA #####

keyremarks <- dw2020 %>%
  gs_read(ws = "Key Interviews/Remarks") %>%
  clean_names()

keyremarks <- keyremarks %>% 
  mutate(
    date = dmy(date),
    candidate = as.factor(candidate),
    venue = as.factor(venue),
    subject_1 = as.factor(subject_1),
    subject_2 = as.factor(subject_2),
    state = as.factor(state),
    on_cam = as.factor(on_cam)
  )


# set time object set to EST
d <- Sys.Date()
# d <- .POSIXct(d, "EST")
  
t <- Sys.time()
t <- .POSIXct(t, "EST")

```




Key SOTs & Remarks 
=====================================
To filter, click on the boxes above the column names. To sort, use the up/down arrows by the column names.

Row {data-height=1000}
-----------------------------------------------------------------------

```{r}

remarks_big <- keyremarks %>% 
  select(candidate,
         date,
         venue,
         city,
         state,
         on_cam,
         ms_number,
         subject_1,
         tc_in,
         key_sound,
         subject_2,
         tc_in_2,
         other_sound,
        source_link
          ) %>% 
  mutate(
    on_cam = as.factor(str_to_lower(on_cam))
  ) %>% 
  arrange(desc(date))

datatable(remarks_big,
          rownames = FALSE,
          filter = "top",
          extensions = 'Buttons',
          options = list(searchHighlight = TRUE, bPaginate = FALSE, dom = 'Bfrtip', scrollX=TRUE,scrollY=400, 
     buttons = c('copy', 'excel', 'pdf', 'print')
          )) %>%
  formatDate('date', 'toLocaleDateString') %>%
  formatStyle('candidate', fontWeight = 'bold')



```


