---
output: html_document
resource_files:
- .httr-oauth
rmd_output_metadata:
  rsc_output_files:
    - "events_data.rds"
    - "keyremarks_data.rds"
    - "announcements_data.rds"
    - "dt_detailed_table.rds"
    - "dt_keyremarks.rds"
    - "leafmap_upcomingweek.rds"
    - "leaf_allpasttrips.rds"
    - "leaf_allfuturetrips.rds"
    - "time_updated.rds"
---


# Data Pull Started at `r Sys.time()`

Scheduling a Rmd file with embedded ETL code is really helpful. 
Here we will pull from the 2020 candidate gsheet and create saved files.


```{r setup, include=FALSE}

library(tidyverse)
library(lubridate)
library(janitor)
library(googlesheets)
library(feather)
library(DT)
library(glue)
library(plotly)
library(kableExtra)
library(leaflet)
# library(ggmap)
library(RColorBrewer)
library(htmltools)
library(tigris)
options(tigris_class = "sf")



```

Load in from google sheet and prep dataframe
```{r gsheet_load}

# import data from Google Sheet 

#register DW's 2020 google sheet
dw2020 <- gs_key("1rhCkWIHW3kblAP2H-1A7_123ACCuJLoafGXfnEldYl4")

#read in all the data in the rally/event tab
events <- dw2020 %>% 
  gs_read(ws = "AK VER Rally / Event Tracker") %>% 
  clean_names() 

#set formatting of certain columns
events <- events %>% 
  mutate(
    date = mdy(date),
    thru_date = mdy(thru_date),
    cand_fullname = as.factor(cand_fullname),
    state = as.factor(state),
    cd_if_known = as.factor(cd_if_known),
    event_type = as.factor(event_type),
    cand_fullname = as.factor(cand_fullname),
    cand_lastname = as.factor(cand_lastname),
    sponsor = as.factor(sponsor),
    approx_date = as.factor(approx_date),
    city = as.factor(city)
    )
         


# INTERVIEWS/REMARKS DATA #####

keyremarks <- dw2020 %>%
  gs_read(ws = "Key Interviews/Remarks") %>%
  clean_names()

keyremarks <- keyremarks %>% 
  mutate(
    date = dmy(date),
    candidate = as.factor(candidate),
    venue = as.factor(venue),
    subject_1 = as.factor(subject_1),
    subject_2 = as.factor(subject_2),
    state = as.factor(state),
    on_cam = as.factor(on_cam)
  )


### CANDIDATE ANNOUNCEMENTS DATA ####
announcements <- dw2020 %>%
  gs_read(ws = "Candidate Announcements") %>%
  clean_names() %>% 
  mutate(
    date = mdy(date)
  ) %>% 
  select(-x7, -x8) %>% 
  arrange(desc(date))

### GEOGRAPHIC DATA ####

# # Downloading the shapefiles for states at the lowest resolution from tigris
states <- states(cb=T)


### PRE FAB ELEMENTS #####

## CREATE PRE-FAB DT TABLE FOR FULL DETAILED DATA TAB ####

ev_big <- events %>% 
  select(-cand_restname, -cand_lastname, -cd_if_known, -county) 

dt_detailed_table <- datatable(ev_big,
          rownames = FALSE,
          filter = "top",
          extensions = 'Buttons',
          options = list(bPaginate = FALSE, dom = 'Bfrtip',
     buttons = c('copy', 'csv', 'excel', 'pdf', 'print')
          )) %>%
  formatDate('date', 'toLocaleDateString') %>%
  formatDate('thru_date', 'toLocaleDateString') %>%
  formatStyle('cand_fullname', fontWeight = 'bold')


## CREATE PRE-FAB DT TABLE FOR KEY REMARKS TAB ####

remarks_big <- keyremarks %>% 
  select(candidate,
         date,
         venue,
         city,
         state,
         on_cam,
         ms_number,
         subject_1,
         tc_in,
         key_sound,
         subject_2,
         tc_in_2,
         other_sound,
        source_link
          ) %>% 
  mutate(
    on_cam = as.factor(str_to_lower(on_cam))
  ) %>% 
  arrange(desc(date))

dt_keyremarks <- datatable(remarks_big,
          rownames = FALSE,
          filter = "top",
          extensions = 'Buttons',
          options = list(bPaginate = FALSE, dom = 'Bfrtip', scrollX=TRUE,scrollY=400, 
     buttons = c('copy', 'csv', 'excel', 'pdf', 'print')
          )) %>%
  formatDate('date', 'toLocaleDateString') %>%
  formatStyle('candidate', fontWeight = 'bold')



### map of visits over next week ####

upcoming_states <- events %>% 
  filter(date > Sys.Date(),
         date < (Sys.Date()+7)) %>% 
  group_by(state) %>%
  summarize(total=n()) 

# Now we use the Tigris function geo_join to bring together 
# are the two columns they'll be joined by
states_merged_sb <- geo_join(states, upcoming_states, "STUSPS", "state")

# Creating a color palette based on the number range in the total column
pal <- colorNumeric("YlGn", domain=states_merged_sb$total)

# Getting rid of rows with NA values
# Using the Base R method of filtering subset() because we're dealing with a SpatialPolygonsDataFrame and not a normal data frame, thus filter() wouldn't work
states_merged_sb <- subset(states_merged_sb, !is.na(total))
states_merged_sb$total <- as.integer(states_merged_sb$total)

#create map with hover popups

popup_sb <- paste0("Trips over coming week: ", as.character(states_merged_sb$total))

leafmap_upcomingweek <- leaflet() %>%
  addTiles() %>%
  # setView(-98.483330, 38.712046, zoom = 4) %>% 
  addPolygons(data = states_merged_sb , 
              fillColor = ~pal(states_merged_sb$total), 
              fillOpacity = 0.9, 
              weight = 0.2, 
              smoothFactor = 0.2,
              highlight = highlightOptions(
                weight = 5,
                color = "#666",
                fillOpacity = 0.7,
                bringToFront = TRUE),
              label=popup_sb,
              labelOptions = labelOptions(
                style = list("font-weight" = "normal", padding = "3px 8px"),
                textsize = "15px",
                direction = "auto")) %>%
  addLegend(pal = pal, 
            values = states_merged_sb$total,
            bins = 4,
            position = "bottomright", 
            title = "Total trips", 
            labFormat = labelFormat(digits = 0)
            )



### map of visits of ALL trips in the past ####

upcoming_states <- events %>% 
  filter(date <= Sys.Date()) %>% 
  group_by(state) %>%
  summarize(total=n()) 

# Now we use the Tigris function geo_join to bring together 
# are the two columns they'll be joined by
states_merged_sb <- geo_join(states, upcoming_states, "STUSPS", "state")

# Creating a color palette based on the number range in the total column
pal <- colorNumeric("YlOrRd", domain=states_merged_sb$total)

# Getting rid of rows with NA values
# Using the Base R method of filtering subset() because we're dealing with a SpatialPolygonsDataFrame and not a normal data frame, thus filter() wouldn't work
states_merged_sb <- subset(states_merged_sb, !is.na(total))
states_merged_sb$total <- as.integer(states_merged_sb$total)

#create map with hover popups

popup_sb <- paste0("Trips: ", as.character(states_merged_sb$total))

leaf_allpasttrips <- leaflet() %>%
  addTiles() %>%
  # setView(-98.483330, 38.712046, zoom = 4) %>% 
  addPolygons(data = states_merged_sb , 
              fillColor = ~pal(states_merged_sb$total), 
              fillOpacity = 0.9, 
              weight = 0.2, 
              smoothFactor = 0.2,
              highlight = highlightOptions(
                weight = 5,
                color = "#666",
                fillOpacity = 0.7,
                bringToFront = TRUE),
              label=popup_sb,
              labelOptions = labelOptions(
                style = list("font-weight" = "normal", padding = "3px 8px"),
                textsize = "15px",
                direction = "auto")) %>%
  addLegend(pal = pal, 
            values = states_merged_sb$total,
            # bins = 4,
            position = "bottomright", 
            title = "Total trips", 
            labFormat = labelFormat(digits = 0)
            )


### map of visits of ALL trips in the future ####

upcoming_states <- events %>% 
  filter(date > Sys.Date()) %>% 
  group_by(state) %>%
  summarize(total=n()) 

# Now we use the Tigris function geo_join to bring together 
# are the two columns they'll be joined by
states_merged_sb <- geo_join(states, upcoming_states, "STUSPS", "state")

# Creating a color palette based on the number range in the total column
pal <- colorNumeric("YlGn", domain=states_merged_sb$total)

# Getting rid of rows with NA values
# Using the Base R method of filtering subset() because we're dealing with a SpatialPolygonsDataFrame and not a normal data frame, thus filter() wouldn't work
states_merged_sb <- subset(states_merged_sb, !is.na(total))
states_merged_sb$total <- as.integer(states_merged_sb$total)

#create map with hover popups

popup_sb <- paste0("Upcoming trips: ", as.character(states_merged_sb$total))

leaf_allfuturetrips <- leaflet() %>%
  addTiles() %>%
  # setView(-98.483330, 38.712046, zoom = 4) %>% 
  addPolygons(data = states_merged_sb , 
              fillColor = ~pal(states_merged_sb$total), 
              fillOpacity = 0.9, 
              weight = 0.2, 
              smoothFactor = 0.2,
              highlight = highlightOptions(
                weight = 5,
                color = "#666",
                fillOpacity = 0.7,
                bringToFront = TRUE),
              label=popup_sb,
              labelOptions = labelOptions(
                style = list("font-weight" = "normal", padding = "3px 8px"),
                textsize = "15px",
                direction = "auto")) %>%
  addLegend(pal = pal, 
            values = states_merged_sb$total,
            # bins = 4,
            position = "bottomright", 
            title = "Total trips", 
            labFormat = labelFormat(digits = 0)
            )

## save timestamp ####
time_updated <- Sys.time()
time_updated <- .POSIXct(time_updated, "EST")

```


Write to files

```{r save_files}

# write results to files
saveRDS(events, "events_data.rds")
saveRDS(keyremarks, "keyremarks_data.rds")
saveRDS(announcements, "announcements_data.rds")
saveRDS(dt_detailed_table, "dt_detailed_table.rds")
saveRDS(dt_keyremarks, "dt_keyremarks.rds")
saveRDS(leafmap_upcomingweek, "leafmap_upcomingweek.rds")
saveRDS(leaf_allpasttrips, "leaf_allpasttrips.rds")
saveRDS(leaf_allfuturetrips, "leaf_allfuturetrips.rds")
saveRDS(time_updated, "time_updated.rds")


```


