---
output: html_document
resource_files:
- .httr-oauth
rmd_output_metadata:
  rsc_output_files:
    - "data.feather"
---

# Data Pull Started at `r Sys.time()`

Scheduling a Rmd file with embedded ETL code is really helpful. 
Here we will pull from the 2020 candidate gsheet and create feather saved feather files.


```{r setup, include=FALSE}

library(tidyverse)
library(lubridate)
library(janitor)
library(googlesheets)
library(feather)

```

Load in from google sheet and prep dataframe
```{r gsheet_load}

# import data from Google Sheet 

#register DW's 2020 google sheet
dw2020 <- gs_key("1rhCkWIHW3kblAP2H-1A7_123ACCuJLoafGXfnEldYl4")

#read in all the data in the rally/event tab
events <- dw2020 %>% 
  gs_read(ws = "AK VER Rally / Event Tracker") %>% 
  clean_names() 

#set formatting of certain columns
events <- events %>% 
  mutate(
    date = mdy(date),
    thru_date = mdy(thru_date),
    cand_fullname = as.factor(cand_fullname),
    state = as.factor(state),
    cd_if_known = as.factor(cd_if_known),
    event_type = as.factor(event_type),
    cand_fullname = as.factor(cand_fullname),
    cand_lastname = as.factor(cand_lastname),
    sponsor = as.factor(sponsor)
         )


# INTERVIEWS/REMARKS DATA #####

keyremarks <- dw2020 %>%
  gs_read(ws = "Key Interviews/Remarks") %>%
  clean_names()

keyremarks <- keyremarks %>% 
  mutate(
    date = dmy(date),
    candidate = as.factor(candidate),
    venue = as.factor(venue),
    subject_1 = as.factor(subject_1),
    subject_2 = as.factor(subject_2),
    state = as.factor(state),
    on_cam = as.factor(on_cam)
  )


### CANDIDATE ANNOUNCEMENTS DATA ####
announcements <- dw2020 %>%
  gs_read(ws = "Candidate Announcements") %>%
  clean_names() %>% 
  mutate(
    date = mdy(date)
  ) %>% 
  select(-x7, -x8) %>% 
  arrange(desc(date))


```


Write to feather files

```{r feather_file}

# write results to feather file
write_feather(events, "events_data.feather")
write_feather(keyremarks, "keyremarks_data.feather")
write_feather(announcements, "announcements_data.feather")

```


